### ISSUE TITLE
How to actually use mobx-persist-store? 

### ISSUE THREAD

**Issue by Danscap** [quarrant/mobx-persist-store#6]
Specifically the usage without decorators.

```.js
import { action, observable, computed, decorate } from 'mobx';
import { persistence, useClear, useDisposers, isSynchronized, StorageAdapter } from 'mobx-persist-store';

function readStore(name) {
  return new Promise((resolve) => {
    const data = localStorage.getItem(name);
    resolve(JSON.parse(data));
  });
}

function writeStore(name, content) {
  return new Promise((resolve) => {
    localStorage.setItem(name, JSON.stringify(content));
    resolve();
  });
}

class CounterStore {
  counter: number = 0;

  tickCounter = () => {
    this.counter = this.counter + 1;
  };

  clearStore = () => {
    useClear(this)
  }

  persistDespose = () => {
    useDisposers(this)
  }

  get isSynchronized() => {
    return isSynchronized(this)
  }
}

decorator(CounterStore, {
  counter: observable,
  tickCounter: action,
  clearStore: action,
  persistDispose: action,
  isSynchronized: computed
})

persistence({
  name: 'CounterStore',
  properties: ['counter'],
  adapter: new StorageAdapter({
    read: readStore,
    write: writeStore,
  }),
  reactionOptions: { // optional
    delay: 2000
  },
})(CounterStore);

export default new CounterStore();
```

Questions:

1`)decorator` function is a typo and should be `decorate`, correct?

2)adding observables means we have to add to the properties array in the persistence function?
2.5) `counter: number = 0` .. could this be written as `counter = 0` ?

3)how to actually write and read from the store? How to use the function?

In normal mobx, we could just write 

`store.observable = new_value` .

What to do here? How do we use the readStore and writeStore functions?

4) What are the other functions for: specifically isSynchronized, persistDespose?

Is there documentation that explains all of this?

Thank you. I am having issues getting mobx-persist-store to work because I simply do not understand it.

**Comment by quarrant** [comment]
1. Yes, you're right. It's mistake

2. Yes, if you want to persist this properties

2.5 Yes, type will be inferred (Hello from typescript)

3. persistence creates a reaction to changes in observable properties. (https://github.com/quarrant/mobx-persist-store/blob/master/src/persistenceDecorator.ts#L55) And the StorageAdapter read/write any changes through your functions. (https://github.com/quarrant/mobx-persist-store/blob/master/src/persistenceDecorator.ts#L57 and https://github.com/quarrant/mobx-persist-store/blob/master/src/persistenceDecorator.ts#L63)

4. `isSynchronized` indicates whether the storage is restored since cache reading is asynchronous. `useClear` remove all cache from store. And `useDisposers` stop persistence for store.


```typescript
class Store {
  onSynchronized = () => {
    return new Promise((resolve) => {
      this.initializeDisposer = autorun(() => {
        if (isSynchronized(this)) {
          if (this.initializeDisposer) {
            this.initializeDisposer();
          }
          resolve();
        }
      });
    });
  };
}

const store = new Store()

store.onSynchronized().then(() => {
  // the code will be called after the store is restored from cache
})
```

I will try to find time to write detailed documentation...
