### ISSUE TITLE
[BUG] version 1.1.0 package is empty

### ISSUE THREAD

**Issue by PeterJSung** [quarrant/mobx-persist-store#95]
when we install mobx-persist-store (v 1.1.0), there is no module definition in esm.* folder.

definition file is located in lib/esm*/src folder, and esm root has only fake library.

thank you.

![스크린샷 2022-08-31 오후 8 33 49](https://user-images.githubusercontent.com/14996546/187669561-8524cd76-dd5d-4f9e-a4f1-d52f54243a3f.png)

**Comment by tobua** [comment]
Just ran into the same issue after updating. Looks like this has happened because a new TS file called `setup-fake-timers.ts` has been added to the root and now the contents are published with an additional `src` folder, see here on [unpkg](https://unpkg.com/browse/mobx-persist-store@1.1.0/lib/esm2017/).

I don't see the file being used, maybe it can be removed. Otherwise moving it into src or adapting the "include" in tsconfig could also fix the issue.

Thanks!

**Comment by quarrant** [comment]
Thank you. This bug was fixed in version 1.1.2
